languageCode = "fr"
languageName = "Francais"
weight = 1
title = "AlexanderAmarok"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "static/favicon-32x32.png"
  secondaryLogo = "static/favicon-32x32.png"
  description = "AlexanderAmarok's personal portfolio"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Alexander Amarok"
  image = "img/amarok_logo.jpg"
  headline = "Je fais du pixel art et des stickers, tout ça depuis le royaume de Belgique"
  bio = ""
  links = [
    { bluesky = "https://bsky.app/profile/alexanderamarok.bsky.social" },
    { discord = "https://discord.gg/invitecode" },
    { instagram = "https://www.instagram.com/alexanderamarok/" },
    { mastodon = "https://piaille.fr/@AlexanderAmarok" },
    { steam = "https://steamcommunity.com/profiles/76561198098437417/" },
    { twitch = "https://www.twitch.tv/alexanderamarok" },
    { x-twitter = "https://twitter.com/AlexanderAmarok" },
    { youtube = "https://www.youtube.com/channel/UCTLpWpgH2v1_2jjGLMToP4A" },
    { ko-fi = "https://ko-fi.com/alexanderamarok0035" },
  ]
